version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
#  3306 - занят локальной БД, пробросил на 3308 для IDEA

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"